name: 'osm'
version: '1.0.0'

profile: 'osm'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

models:
  eia:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

seeds: